addLayer("achievements", {
    name: "Achievements", // This is optional, only used in a few places, If absent it just uses the layer id.
    symbol: "Ach", // This appears on the layer's node. Default is the id with the first letter capitalized
    row: "side",
    position: 0, // Horizontal position within a row. By default it uses the layer id and sorts in alphabetical order
    startData() { return {
        unlocked: true,
    }},
    achievements: {
        // Part 1
        1: {
            name: "First Reset<br><small>(of many)</small>",
            image: "resources/achievements/1_01.png",
            tooltip: "<h3>First Reset <small>(of many)</small></h3><hr style='margin-bottom:4px'>Obtain your first rank.",
            color: "white",
            complete() {return hasUpgrade("p", 17)},
            unlocked: true,
        },
        2: {
            name: "Small Beginnings",
            image: "resources/achievements/1_02.png",
            tooltip: "<h3>Small Beginnings</h3><hr style='margin-bottom:4px'>Obtain your first tier.<br><br>Reward: Ranks are 20% cheaper.",
            color: "white",
            complete() {return hasUpgrade("p", 18)},
            unlocked: true,
            marked: true,
        },
        3: {
            name: "Seperate Doubling",
            image: "resources/achievements/1_03.png",
            tooltip: "<h3>Seperate Doubling</h3><hr style='margin-bottom:4px'>Reach x2 points from factors.",
            color: "white",
            complete() {return hasUpgrade("p", 15) || hasUpgrade("cs", 201)},
            unlocked: true,
        },
        4: {
            name: "Tetr, Hold the Mino",
            image: "resources/achievements/1_04.png",
            tooltip: "<h3>Tetr, Hold the Mino</h3><hr style='margin-bottom:4px'>Obtain your first tetr.<br><br>Reward: Ranks and Tiers are<br>15% cheaper.",
            color: "white",
            complete() {return hasUpgrade("p", 22) || hasMilestone("s", 19)},
            unlocked: true,
            marked: true,
        },
        5: {
            name: "Prestigious",
            image: "resources/achievements/1_05.png",
            tooltip: "<h3>Prestigious</h3><hr style='margin-bottom:4px'>Do your first prestige reset.<br><br>Reward: Ranks, Tiers, and Tetrs<br>are 10% cheaper.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        6: {
            name: "Octuple Factors",
            image: "resources/achievements/1_06.png",
            tooltip: "<h3>Octuple Factors</h3><hr style='margin-bottom:4px'>Buy a Factor VIII.",
            color: "white",
            complete() {return hasUpgrade("p", 15) || hasUpgrade("cs", 201)},
            unlocked: true,
        },
        7: {
            name: "Factor Powered",
            image: "resources/achievements/1_07.png",
            tooltip: "<h3>Factor Powered</h3><hr style='margin-bottom:4px'>Buy a Power Factor.",
            color: "white",
            complete() {return hasUpgrade("p", 21) || hasUpgrade("cs", 201)},
            unlocked: true,
        },
        8: {
            name: "Leaf Leavings",
            image: "resources/achievements/1_08.png",
            tooltip: "<h3>Leaf Leavings</h3><hr style='margin-bottom:4px'>Buy a Leaf Producer.",
            color: "white",
            complete() {return hasMilestone("r", 12)},
            unlocked: true,
        },
        9: {
            name: "Longer Blades",
            image: "resources/achievements/1_09.png",
            tooltip: "<h3>Longer Blades</h3><hr style='margin-bottom:4px'>Increase your grass value.<br><br>Reward: Grass spawn time<br>reduced by 10%.",
            color: "white",
            complete() {return hasMilestone("r", 13)},
            unlocked: true,
            marked: true,
        },
        10: {
            name: "Pent Up",
            image: "resources/achievements/1_10.png",
            tooltip: "<h3>Pent Up</h3><hr style='margin-bottom:4px'>Obtain your first pent.",
            color: "white",
            complete() {return hasUpgrade("i", 32) || inChallenge("ip", 14)},
            unlocked: true,
        },
        11: {
            name: "Natural Dormancy",
            image: "resources/achievements/1_11.png",
            tooltip: "<h3>Natural Dormancy</h3><hr style='margin-bottom:4px'>Unlock golden grass.<br><br>Reward: Increase grass value by 25%.",
            color: "white",
            complete() {return hasMilestone('r', 15) || hasMilestone("ip", 11)},
            unlocked: true,
            marked: true,
        },
        12: {
            name: "Golden Scam",
            image: "resources/achievements/1_12.png",
            tooltip: "<h3>Golden Scam</h3><hr style='margin-bottom:4px'>Increase your golden grass value.<br><br>Reward: Golden grass spawn time<br>reduced by 10%.",
            color: "white",
            complete() {return hasMilestone('r', 13)},
            unlocked: true,
            marked: true,
        },
        13: {
            name: "Bugged Buffs",
            image: "resources/achievements/1_13.png",
            tooltip: "<h3>Bugged Buffs</h3><hr style='margin-bottom:4px'>Do your first grasshop reset.",
            color: "white",
            unlocked: true,
        },
        14: {
            name: "Unranked",
            image: "resources/achievements/1_14.png",
            tooltip: "<h3>Unranked</h3><hr style='margin-bottom:4px'>Prestige without having any<br>ranks/tiers/tetrs.<br><br>Reward: Increase grass value<br>by 50%.",
            color: "white",
            complete() {return hasMilestone('r', 15) || hasMilestone("ip", 11)},
            unlocked: true,
            marked: true,
        },
        15: {
            name: "Small Returns",
            image: "resources/achievements/1_15.png",
            tooltip: "<h3>Small Returns</h3><hr style='margin-bottom:4px'>Buy a grass factor.<br><br>Reward: Increase fertilizer<br>gain by 50%.",
            color: "white",
            complete() {return hasMilestone("r", 16) || hasUpgrade("cs", 201)},
            unlocked: true,
            marked: true,
        },
        16: {
            name: "Shockingly Powerful",
            image: "resources/achievements/1_16.png",
            tooltip: "<h3>Shockingly Powerful</h3><hr style='margin-bottom:4px'>Buy a Factor Study I.",
            color: "white",
            complete() {return hasMilestone("ip", 17) || getBuyableAmount("gh", 16).gte(20)},
            unlocked: true,
        },
        17: {
            name: "Hello World",
            image: "resources/achievements/1_17.png",
            tooltip: "<h3>Hello World</h3><hr style='margin-bottom:4px'>Do your first<br>code experience reset.<br><br>Reward: Decrease pent<br>requirement by /8.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        18: {
            name: "Timed Gains",
            image: "resources/achievements/1_18.png",
            tooltip: "<h3>Timed Gains</h3><hr style='margin-bottom:4px'>Unlock Check Back.",
            color: "white",
            complete() {return hasMilestone("ip", 19) || hasMilestone("s", 17)},
            unlocked: true,
        },
        19: {
            name: "Lucky Gains",
            image: "resources/achievements/1_19.png",
            tooltip: "<h3>Lucky Gains</h3><hr style='margin-bottom:4px'>Enable dice OTF.",
            color: "white",
            unlocked: true,
        },
        20: {
            name: "Multiplied Chances",
            image: "resources/achievements/1_20.png",
            tooltip: "<h3>Multiplied Chances</h3><hr style='margin-bottom:4px'>Gain a second die.<br><br>Reward: Increase dice point<br>gain by 25%.",
            color: "white",
            complete() {return hasUpgrade("d", 11) || hasUpgrade("tad", 13)},
            unlocked: true,
            marked: true,
        },
        21: {
            name: "New Friends",
            image: "resources/achievements/1_21.png",
            tooltip: "<h3>New Friends</h3><hr style='margin-bottom:4px'>Gain your first pet.",
            color: "white",
            unlocked: true,
        },
        22: {
            name: "All In",
            image: "resources/achievements/1_22.png",
            tooltip: "<h3>All In</h3><hr style='margin-bottom:4px'>Do a booster dice roll<br>while having all t1 boost<br>effects be greater then 1.<br><br>Reward: Unlock a toggle for<br>faster booster rolls.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        23: {
            name: "Swarmed",
            image: "resources/achievements/1_23.png",
            tooltip: "<h3>Swarmed</h3><hr style='margin-bottom:4px'>Reset for over<br>1e25 grasshoppers<br><br>Reward: Double<br>grasshopper gain.",
            color: "white",
            unlocked: true,
            marked: true,
        },
        24: {
            name: "Pent-Uncapped",
            image: "resources/achievements/1_24.png",
            tooltip: "<h3>Pent-Uncapped</h3><hr style='margin-bottom:4px'>Gain a 31st pent.",
            color: "white",
            complete() {return hasUpgrade("i", 32) || inChallenge("ip", 14)},
            unlocked: true,
        },
        // Part 2
        101: {
            name: "To Infinity",
            image: "resources/achievements/2_01.png",
            tooltip: "<h3>To Infinity</h3><hr style='margin-bottom:4px'>Reach infinity.",
            color: "#ffbf00",
            unlocked: true,
        },
        102: {
            name: "New Dimensions",
            image: "resources/achievements/2_02.png",
            tooltip: "<h3>New Dimensions</h3><hr style='margin-bottom:4px'>Do your first dimension<br>boost.",
            color: "#ffbf00",
            unlocked: true,
        },
        103: {
            name: "Fueled Gains",
            image: "resources/achievements/2_03.png",
            tooltip: "<h3>Fueled Gains</h3><hr style='margin-bottom:4px'>Do your first rocket<br>fuel reset.",
            color: "#ffbf00",
            unlocked: true,
        },
        104: {
            name: "Paid Friends",
            image: "resources/achievements/2_04.png",
            tooltip: "<h3>Paid Friends</h3><hr style='margin-bottom:4px'>Buy a pet from the<br>pet shop.<br><br>Reward: +5% crate roll<br>chance.<br><small>(Chance to roll more times)</small>",
            color: "#ffbf00",
            unlocked: true,
            marked: true,
        },
        105: {
            name: "Kept Time",
            image: "resources/achievements/2_05.png",
            tooltip: "<h3>Kept Time</h3><hr style='margin-bottom:4px'>Reach the third<br>infinity milestone.",
            color: "#ffbf00",
            unlocked: true,
        },
        106: {
            name: "Galactic Gains",
            image: "resources/achievements/2_06.png",
            tooltip: "<h3>Galactic Gains</h3><hr style='margin-bottom:4px'>Buy an antimatter galaxy.",
            color: "#ffbf00",
            unlocked: true,
        },
        107: {
            name: "Unnecessary Feature",
            image: "resources/achievements/2_07.png",
            tooltip: "<h3>Unnecessary Feature</h3><hr style='margin-bottom:4px'>Beat infinity challenge 1.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 11)},
            unlocked: true,
            marked: true,
        },
        108: {
            name: "Pest Lover",
            image: "resources/achievements/2_08.png",
            tooltip: "<h3>Pest Lover</h3><hr style='margin-bottom:4px'>Obtain 250,000 pests.<br><br>Reward: Grasshops remove<br>twice as many pests.",
            color: "#ffbf00",
            unlocked: true,
            marked: true,
        },
        109: {
            name: "Pest Exterminator",
            image: "resources/achievements/2_09.png",
            tooltip: "<h3>Pest Exterminator</h3><hr style='margin-bottom:4px'>Beat infinity challenge 2.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 12)},
            unlocked: true,
            marked: true,
        },
        110: {
            name: "Rough Resets",
            image: "resources/achievements/2_10.png",
            tooltip: "<h3>Rough Resets</h3><hr style='margin-bottom:4px'>Reset for over<br>6 β-Provenance.<br><br>Reward: β-Provenances<br>are 10% cheaper.",
            color: "#ffbf00",
            complete() {return hasMilestone("hre", 6)},
            unlocked: true,
            marked: true,
        },
        111: {
            name: "Hexing Challenge",
            image: "resources/achievements/2_11.png",
            tooltip: "<h3>Hexing Challenge</h3><hr style='margin-bottom:4px'>Beat infinity challenge 3.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 13)},
            unlocked: true,
            marked: true,
        },
        112: {
            name: "Wrong Goal!",
            image: "resources/achievements/2_12.png",
            tooltip: "<h3>Wrong Goal!</h3><hr style='margin-bottom:4px'>Reach infinity in<br>infinity challenge 4.<br><br>Reward: Decrease pent<br>requirement by /10",
            color: "#ffbf00",
            unlocked: true,
            marked: true,
        },
        113: {
            name: "Pent Down",
            image: "resources/achievements/2_13.png",
            tooltip: "<h3>Pent Down</h3><hr style='margin-bottom:4px'>Beat infinity challenge 4.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 14)},
            unlocked: true,
            marked: true,
        },
        114: {
            name: "Doublin'",
            image: "resources/achievements/2_14.png",
            tooltip: "<h3>Doublin'</h3><hr style='margin-bottom:4px'>Buy an IP Doubler.",
            color: "#ffbf00",
            unlocked: true,
        },
        115: {
            name: "Not Very Boosty",
            image: "resources/achievements/2_15.png",
            tooltip: "<h3>Not Very Boosty</h3><hr style='margin-bottom:4px'>Buy a \"Challenge Dice<br>Boosty!!! :D\".<br><br>Reward: Double Dice Points.",
            color: "#ffbf00",
            unlocked: true,
            marked: true,
        },
        116: {
            name: "Dicey Challenge",
            image: "resources/achievements/2_16.png",
            tooltip: "<h3>Dicey Challenge</h3><hr style='margin-bottom:4px'>Beat infinity challenge 5.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 15)},
            unlocked: true,
            marked: true,
        },
        117: {
            name: "Golden Time",
            image: "resources/achievements/2_17.png",
            tooltip: "<h3>Golden Time</h3><hr style='margin-bottom:4px'>Evolve Unsmith.",
            color: "#ffbf00",
            complete() {return getLevelableAmount("pet", 1103).gt(0)},
            unlocked: true,
        },
        118: {
            name: "Automated Scripts",
            image: "resources/achievements/2_18.png",
            tooltip: "<h3>Automated Scripts</h3><hr style='margin-bottom:4px'>Reach the twelfth<br>infinity milestone.",
            color: "#ffbf00",
            unlocked: true,
        },
        119: {
            name: "Requirement Met?",
            image: "resources/achievements/2_19.png",
            tooltip: "<h3>Requirement Met?</h3><hr style='margin-bottom:4px'>Reset for over<br>1e15 rocket fuel.",
            color: "#ffbf00",
            unlocked: true,
        },
        120: {
            name: "Nightmare Fuel",
            image: "resources/achievements/2_20.png",
            tooltip: "<h3>Nightmare Fuel</h3><hr style='margin-bottom:4px'>Beat infinity challenge 6.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 16)},
            unlocked: true,
            marked: true,
        },
        121: {
            name: "Bless Up",
            image: "resources/achievements/2_21.png",
            tooltip: "<h3>Bless Up</h3><hr style='margin-bottom:4px'>Do your first<br>blessing reset.",
            color: "#ffbf00",
            unlocked: true,
        },
        122: {
            name: "ShardNG",
            image: "resources/achievements/2_22.png",
            tooltip: "<h3>ShardNG</h3><hr style='margin-bottom:4px'>Beat infinity challenge 7.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 17)},
            unlocked: true,
            marked: true,
        },
        123: {
            name: "4x4",
            image: "resources/achievements/2_23.png",
            tooltip: "<h3>4x4</h3><hr style='margin-bottom:4px'>Reach 4 4th dimensions<br>without any dim-boosts<br>in infinity challenge 8.<br><br>Reward: Double Antimatter<br>Dimensions.",
            color: "#ffbf00",
            unlocked: true,
            marked: true,
        },
        124: {
            name: "The 8th Dimension is a lie",
            image: "resources/achievements/2_24.png",
            tooltip: "<h3>The 8th Dimension is a lie</h3><hr style='margin-bottom:4px'>Beat infinity challenge 8.<br><br>Reward: x1.1 Infinities.",
            color: "#ffbf00",
            complete() {return hasChallenge("ip", 18)},
            unlocked: true,
            marked: true,
        },
        // Part 3
        201: {
            name: "To...  Negative Infinity?",
            image: "resources/achievements/3_01.png",
            tooltip: "<h3>To...  Negative Infinity?</h3><hr style='margin-bottom:4px'>Reach negative infinity.",
            color: "#b2d8d8",
            unlocked: true,
        },
        202: {
            name: "Kept Dimensions",
            image: "resources/achievements/3_02.png",
            tooltip: "<h3>Kept Dimensions</h3><hr style='margin-bottom:4px'>Buy a Dimboost Reserve.",
            color: "#b2d8d8",
            complete() {return getBuyableAmount("ta", 38).gte(1)},
            unlocked: true,
        },
        203: {
            name: "Power Boost",
            image: "resources/achievements/3_03.png",
            tooltip: "<h3>Power Boost</h3><hr style='margin-bottom:4px'>Buy the 3rd NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 13)},
            unlocked: true,
        },
        204: {
            name: "Age of Automation",
            image: "resources/achievements/3_04.png",
            tooltip: "<h3>Age of Automation</h3><hr style='margin-bottom:4px'>Have at least 1 divider<br>for each autobuyer.<br><br>Reward: +1 base NIP gain.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        205: {
            name: "New Blessings",
            image: "resources/achievements/3_05.png",
            tooltip: "<h3>New Blessings</h3><hr style='margin-bottom:4px'>Buy the 5th NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 15)},
            unlocked: true,
        },
        206: {
            name: "Cursed!",
            image: "resources/achievements/3_06.png",
            tooltip: "<h3>Cursed!</h3><hr style='margin-bottom:4px'>Buy the 6th NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 16)},
            unlocked: true,
        },
        207: {
            name: "OTF Synergy",
            image: "resources/achievements/3_07.png",
            tooltip: "<h3>OTF Synergy</h3><hr style='margin-bottom:4px'>Buy the 7th NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 17)},
            unlocked: true,
        },
        208: {
            name: "More XP",
            image: "resources/achievements/3_08.png",
            tooltip: "<h3>More XP</h3><hr style='margin-bottom:4px'>Do your first XPBoost reset.<br><br>Reward: Increase check back<br>XP gain by 50%.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        209: {
            name: "Who needs galaxies anyway?",
            image: "resources/achievements/3_09.png",
            tooltip: "<h3>Who needs galaxies anyway?</h3><hr style='margin-bottom:4px'>Reach negative infinity without<br>buying any antimatter galaxies.<br><br>Reward: +1 base NIP gain.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        210: {
            name: "Amazing Grace",
            image: "resources/achievements/3_10.png",
            tooltip: "<h3>Amazing Grace</h3><hr style='margin-bottom:4px'>Buy the 8th NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 18)},
            unlocked: true,
        },
        211: {
            name: "Fullmetal Infinities",
            image: "resources/achievements/3_11.png",
            tooltip: "<h3>Fullmetal Infinities</h3><hr style='margin-bottom:4px'>Buy the first 16<br>infinity upgrades.<br><br>Reward: Increase IP<br>gain by 50%.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        212: {
            name: "OTFs and NIP, Oh My!",
            image: "resources/achievements/3_12.png",
            tooltip: "<h3>OTFs and NIP, Oh My!</h3><hr style='margin-bottom:4px'>Buy the 9th NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 19)},
            unlocked: true,
        },
        213: {
            name: "Tav's Domain",
            image: "resources/achievements/3_13.png",
            tooltip: "<h3>Tav's Domain</h3><hr style='margin-bottom:4px'>Buy the 10th NIP upgrade.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("ta", 21)},
            unlocked: true,
        },
        214: {
            name: "You have collapsed!",
            image: "resources/achievements/3_14.png",
            tooltip: "<h3>You have collapsed!</h3><hr style='margin-bottom:4px'>Collapse Tav's Domain.<br><br>Reward: +1 base NIP gain.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        215: {
            name: "Domain Expansion",
            image: "resources/achievements/3_15.png",
            tooltip: "<h3>Domain Expansion</h3><hr style='margin-bottom:4px'>Buy the infinitum upgrade in<br>row 1, column 5.",
            color: "#b2d8d8",
            complete() {return hasUpgrade("tad", 115)},
            unlocked: true,
        },
        216: {
            name: "A little harder...",
            image: "resources/achievements/3_16.png",
            tooltip: "<h3>A little harder...</h3><hr style='margin-bottom:4px'>Collapse Tav's Domain with a<br>cap of at least 1e6 matter.<br><br>Reward: Increase matter<br>gain by 25%.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        217: {
            name: "A step up...",
            image: "resources/achievements/3_17.png",
            tooltip: "<h3>A step up...</h3><hr style='margin-bottom:4px'>Collapse Tav's Domain with a<br>cap of at least 1e7 matter.<br><br>Reward: Increase matter<br>gain by 25%.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        218: {
            name: "Not an AD Ach 34 Copy",
            image: "resources/achievements/3_18.png",
            tooltip: "<h3>Not an AD Ach 34 Copy</h3><hr style='margin-bottom:4px'>Reach negative infinity<br>without any 8th dimensions.<br><br>Reward: +1 base NIP gain.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        219: {
            name: "Compress!",
            image: "resources/achievements/3_19.png",
            tooltip: "<h3>Compress!</h3><hr style='margin-bottom:4px'>Do your first<br>compression reset.<br><br>Reward: Increase matter<br>gain by 50%.",
            color: "#b2d8d8",
            complete() {return player.tad.altInfinities.disfigured.milestone.gte(3)},
            unlocked: true,
            marked: true,
        },
        220: {
            name: "New Effects",
            image: "resources/achievements/3_20.png",
            tooltip: "<h3>New Effects</h3><hr style='margin-bottom:4px'>Buy the infinitum upgrade in<br>row 3, column 3.<br><br>Reward: Increase matter<br>gain by 50%.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        221: {
            name: "Infinity Conversion",
            image: "resources/achievements/3_21.png",
            tooltip: "<h3>Infinity Conversion</h3><hr style='margin-bottom:4px'>Create an alternative<br>infinity.<br><br>Reward: Increase matter<br>gain by 50%.",
            color: "#b2d8d8",
            complete() {return player.tad.altInfinities.broken.amount.gte(1) || player.tad.altInfinities.shattered.amount.gte(1) || player.tad.altInfinities.fragmented.amount.gte(1)},
            unlocked: true,
            marked: true,
        },
        222: {
            name: "Centfinitum",
            image: "resources/achievements/3_22.png",
            tooltip: "<h3>Centfinitum</h3><hr style='margin-bottom:4px'>Have at least 100 infinitum.<br><br>Reward: Increase infinitum<br>gain by 50%.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        223: {
            name: "Seriously?",
            image: "resources/achievements/3_23.png",
            tooltip: "<h3>Seriously?</h3><hr style='margin-bottom:4px'>Reach negative infinity without<br>any 7th or 8th dimensions.<br><br>Reward: +1 base NIP gain.",
            color: "#b2d8d8",
            unlocked: true,
            marked: true,
        },
        224: {
            name: "Goodbye, Friend...",
            image: "resources/achievements/3_24.png",
            tooltip: "<h3>Goodbye, Friend...</h3><hr style='margin-bottom:4px'>Kill Tav.",
            color: "#b2d8d8",
            complete() {return player.in.unlockedBreak},
            unlocked: true,
        },
        // Part 4
        301: {
            name: "Wait, THAT'S AN OTF??!!?!",
            image: "resources/achievements/4_01.png",
            tooltip: "<h3>Wait, THAT'S AN OTF??!!?!</h3><hr style='margin-bottom:4px'>Break infinity.<br><br>Reward: Double IP gain.",
            color: "#2b7f0a",
            complete() {return player.po.breakInfinity},
            unlocked: true,
            marked: true,
        },
        302: {
            name: "Primary Pollinators",
            image: "resources/achievements/4_02.png",
            tooltip: "<h3>Primary Pollinators</h3><hr style='margin-bottom:4px'>Buy the 4th pollinator<br>upgrade.<br><br>Reward: Increase pollinator<br>gain by 25%.",
            color: "#2b7f0a",
            unlocked: true,
            marked: true,
        },
        303: {
            name: "Auto Alphas",
            image: "resources/achievements/4_03.png",
            tooltip: "<h3>Auto Alphas</h3><hr style='margin-bottom:4px'>Reach 30 refinements.<br><br>Reward: Increase hex point<br>gain by 50%.",
            color: "#2b7f0a",
            unlocked: true,
            marked: true,
        },
        304: {
            name: "Pent Increased?",
            image: "resources/achievements/4_04.png",
            tooltip: "<h3>Pent Increased?</h3><hr style='margin-bottom:4px'>Reach Pent 80.<br><br>Reward: Decrease pent<br>requirement by /100.",
            color: "#2b7f0a",
            unlocked: true,
            marked: true,
        },
        305: {
            name: "Level Slowdown",
            image: "resources/achievements/4_05.png",
            tooltip: "<h3>Level Slowdown</h3><hr style='margin-bottom:4px'>Reach check back<br>level 1,000.<br><br>Reward: Double check<br>back XP gain.",
            color: "#2b7f0a",
            unlocked: true,
            marked: true,
        },
        306: {
            name: "Dark Friends",
            image: "resources/achievements/4_06.png",
            tooltip: "<h3>Dark Friends</h3><hr style='margin-bottom:4px'>Evolve Gwa.",
            color: "#2b7f0a",
            complete() {return getLevelableAmount("pet", 1101).gt(0)},
            unlocked: true,
        },
        307: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        308: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        309: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        310: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        311: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        312: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        313: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        314: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        315: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        316: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        317: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        318: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        319: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        320: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        321: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        322: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        323: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        324: {
            name: "Title",
            image: "resources/achievements/4_00.png",
            tooltip: "<h3>Title</h3><hr style='margin-bottom:4px'>Description",
            color: "#2b7f0a",
            unlocked: true,
        },
        // Part 10
        901: {
            name: "Buzzing Beginnings",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Buzzing Beginnings</h3><hr style='margin-bottom:4px'>Buy your first research",
            color: "#f9c901",
            complete() {return getBuyableAmount("bee", 11).gte(0)},
            unlocked: true,
        },
        902: {
            name: "Picked Poppies",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Picked Poppies</h3><hr style='margin-bottom:4px'>Pick your first<br>red flower<br><br>Reward: +5% BPS",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        903: {
            name: "Red Bouquet",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Red Bouquet</h3><hr style='margin-bottom:4px'>Have at least one of<br>every red circular flower<br><br>Reward: +1 Base Picking Power",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        904: {
            name: "Powdery Pollen",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Powdery Pollen</h3><hr style='margin-bottom:4px'>Choose the pollen path<br><br>Reward: +25% Flower Gain",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        905: {
            name: "Blooming Blue",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Blooming Blue</h3><hr style='margin-bottom:4px'>Pick your first<br>blue flower<br><br>Reward: +10% BPS",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        906: {
            name: "<small>You're telling me a bee made this bread?</small>",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>You're telling me a<br>bee made this bread?</h3><hr style='margin-bottom:4px'>Do your first<br>bee bread reset<br><br>Reward: +50% Pollen Gain",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        907: {
            name: "Pink Pickings",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Pink Pickings</h3><hr style='margin-bottom:4px'>Pick your first<br>pink flower<br><br>Reward: +25% BPS",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        908: {
            name: "Nutritious Nectar",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Nutritious Nectar</h3><hr style='margin-bottom:4px'>Choose the nectar path<br><br>Reward: +0.1 GBE",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        909: {
            name: "Gathered Green",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Gathered Green</h3><hr style='margin-bottom:4px'>Pick your first<br>green flower<br><br>Reward: +10% BPS",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        910: {
            name: "Mitochondria is the ... wait wrong cell",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Mitochondria is the<br>... wait wrong cell</h3><hr style='margin-bottom:4px'>Do your first<br>honey-cell reset<br><br>Reward: +20% Nectar Gain",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        911: {
            name: "Blond Blossom",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Blond Blossom</h3><hr style='margin-bottom:4px'>Pick your first<br>yellow flower<br><br>Reward: +25% BPS",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        912: {
            name: "Not Another One!",
            image: "resources/achievements/10_12.png",
            tooltip: "<h3>Not Another One!</h3><hr style='margin-bottom:4px'>Do an aleph reset<br><br>Reward: Flower timers<br>are 10% faster",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        913: {
            name: "Both Sides",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Both Sides</h3><hr style='margin-bottom:4px'>Do both aleph reset types<br><br>Reward: +50% Aleph Resources",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        914: {
            name: "Oh! That is where I put that!",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Oh! That is where<br>I put that!</h3><hr style='margin-bottom:4px'>Purchase the forgotten<br>pollen upgrade<br><br>Reward: +50% Pollen<br>+20% Nectar",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        915: {
            name: "Infested Domain",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Infested Domain</h3><hr style='margin-bottom:4px'>Gain your first<br>T3 alternate infinity",
            color: "#f9c901",
            unlocked: true,
        },
        916: {
            name: "Break ... what exactly?",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Break ... what exactly?</h3><hr style='margin-bottom:4px'>Expand your hive's limits<br><br>Reward: +25% Pre-Aleph<br>Resources",
            color: "#f9c901",
            complete() {return player.tad.hiveExpand},
            unlocked: true,
            marked: true,
        },
        917: {
            name: "How many nectars are there!?!",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>How many nectars<br>are there!?!</h3><hr style='margin-bottom:4px'>Do your first<br>Nectar ε reset<br><br>Reward: +5% Cell<br>Effect Base",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        918: {
            name: "Do you even care about this?",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Do you even<br>care about this?</h3><hr style='margin-bottom:4px'>Do your first<br>apathy reset",
            color: "#f9c901",
            unlocked: true,
        },
        919: {
            name: "Fully Apathetic",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Fully Apathetic</h3><hr style='margin-bottom:4px'>Expand your hive's<br>limits again<br><br>Reward: +25% Pre-Aleph<br>Resources",
            color: "#f9c901",
            complete() {return hasChallenge("fu", 12)},
            unlocked: true,
            marked: true,
        },
        920: {
            name: "Beyond the Queen",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Beyond the Queen</h3><hr style='margin-bottom:4px'>Gain an empress bee<br><br>Reward: +50% BB Milestone<br>Effectiveness",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        921: {
            name: "Draining Depths",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Draining Depths</h3><hr style='margin-bottom:4px'>Enter depth 4<br><br>Reward: +1 SP",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        922: {
            name: "Wasp War Machine",
            image: "resources/achievements/10_22.png",
            tooltip: "<h3>Wasp War Machine</h3><hr style='margin-bottom:4px'>Obtain Vespasian<br><br>Reward: +1 DMG",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        923: {
            name: "Flying Finale",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Flying Finale</h3><hr style='margin-bottom:4px'>Enter Aleph's Chamber<br><br>Reward: +1 MND",
            color: "#f9c901",
            unlocked: true,
            marked: true,
        },
        924: {
            name: "Regicide",
            image: "resources/achievements/10_00.png",
            tooltip: "<h3>Regicide</h3><hr style='margin-bottom:4px'>Defeat Aleph",
            color: "#f9c901",
            complete() {return player.alephsChamber.milestone[25] > 0},
            unlocked: true,
        },
        1201: {
            name: "Welcome to Inter Space",
            image: "resources/achievements/12_01.png",
            tooltip: "<h3>Welcome to Inter Space</h3><hr style='margin-bottom:4px'>Enter interspace.",
            color: "#994d99",
            complete() {return player.lightRift.interspaceUnlocked},
            unlocked: true,
        },
        1202: {
            name: "Shallow Waters",
            image: "resources/achievements/12_02.png",
            tooltip: "<h3>Shallow Waters</h3><hr style='margin-bottom:4px'>Obtain a β ↻.<br><br>Reward: Gain +1 α ↻<br>on collect after<br>multipliers.",
            color: "#994d99",
            complete() {return player.wel.modules[2].completions.gt(0)},
            unlocked: true,
            marked: true,
        },
        1203: {
            name: "α Thousand of Them",
            image: "resources/achievements/12_03.png",
            tooltip: "<h3>α Thousand of Them</h3><hr style='margin-bottom:4px'>Reach the ↻ effect<br>softcap.<br><br>Reward: Gain 5% more<br>light.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1204: {
            name: "Time Attack",
            image: "resources/achievements/12_04.png",
            tooltip: "<h3>Time Attack</h3><hr style='margin-bottom:4px'>Store a time capsule.<br><br>Reward: Gain 10% more<br>time capsules.",
            color: "#994d99",
            complete() {return player.wel.modules[3].completions.gt(0)},
            unlocked: true,
            marked: true,
        },
        1205: {
            name: "The Deep End",
            image: "resources/achievements/12_05.png",
            tooltip: "<h3>The Deep End</h3><hr style='margin-bottom:4px'>Obtain a γ ↻.<br><br>Reward: Gain +1 β ↻<br>on collect after<br>multipliers.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1206: {
            name: "Every Last Drop",
            image: "resources/achievements/12_06.png",
            tooltip: "<h3>Every Last Drop</h3><hr style='margin-bottom:4px'>Store at least 7 time<br>capsules at once.<br><br>Reward: +1 base time<br>capsules stored.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1207: {
            name: "Prismstigous",
            image: "resources/achievements/12_07.png",
            tooltip: "<h3>Prismstigous</h3><hr style='margin-bottom:4px'>Reset for a prism.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1208: {
            name: "Brick by Brick",
            image: "resources/achievements/12_08.png",
            tooltip: "<h3>Brick by Brick</h3><hr style='margin-bottom:4px'>Get at least 1 ↻ for each<br>of the first three pyramid<br>fountains.<br><br>Reward: Gain 20% more light.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1209: {
            name: "Taking Shape",
            image: "resources/achievements/12_09.png",
            tooltip: "<h3>Taking Shape</h3><hr style='margin-bottom:4px'>Get at least 1 ↻ for each<br>of the first six pyramid<br>fountains.<br><br>Reward: Light fountains<br>are 20% cheaper.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1210: {
            name: "Speed Limit",
            image: "resources/achievements/12_10.png",
            tooltip: "<h3>Speed Limit</h3><hr style='margin-bottom:4px'>Exceed x100 light<br>well speed.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1211: {
            name: "Faster than Light",
            image: "resources/achievements/12_11.png",
            tooltip: "<h3>Faster than Light</h3><hr style='margin-bottom:4px'>Blueshift a light<br>well.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1212: {
            name: "We Could Only Fit Three",
            image: "resources/achievements/12_12.png",
            tooltip: "<h3>We Could Only Fit Three</h3><hr style='margin-bottom:4px'>Get 1 Dodecahedron ↻.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1213: {
            name: "Midnight Zone",
            image: "resources/achievements/12_13.png",
            tooltip: "<h3>Midnight Zone</h3><hr style='margin-bottom:4px'>Obtain a δ ↻.<br><br>Reward: Gain 10%<br>more light well ↻<br>on collect.",
            color: "#994d99",
            complete() {return player.wel.modules[4].completions.gt(0)},
            unlocked: true,
            marked: true,
        },
        1214: {
            name: "First Wonder of Interspace",
            image: "resources/achievements/12_14.png",
            tooltip: "<h3>First Wonder of Interspace</h3><hr style='margin-bottom:4px'>Get at least 1 ↻ for each<br>of the first nine pyramid<br>fountains.<br><br>Reward: Gain 20% more prisms.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1215: {
            name: "Big Time",
            image: "resources/achievements/12_15.png",
            tooltip: "<h3>Big Time</h3><hr style='margin-bottom:4px'>Store at least 7,200<br>time capsules at once.<br><br>Reward: Generate twice<br>as much time energy.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1216: {
            name: "???",
            image: "resources/achievements/12_19.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1217: {
            name: "Ultraviolet",
            image: "resources/achievements/12_16.png",
            tooltip: "<h3>Ultraviolet</h3><hr style='margin-bottom:4px'>Reset for starlight.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1218: {
            name: "Full Marks",
            image: "resources/achievements/12_19.png",
            tooltip: "<h3>Full Marks</h3><hr style='margin-bottom:4px'>Get e100 Light.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1219: {
            name: "awwww kitty!!!",
            image: "resources/achievements/12_17.png",
            tooltip: "<h3>awwww kitty!!!</h3><hr style='margin-bottom:4px'>Unlock goobert.<br><br>Reward: Fragment<br>shop cooldowns<br>are 2% shorter.",
            color: "#994d99",
            complete() {return hasUpgrade("bum", 13)},
            unlocked: true,
            marked: true,
        },
        1220: {
            name: "Those Count?",
            image: "resources/achievements/12_19.png",
            tooltip: "<h3>Those Count?</h3><hr style='margin-bottom:4px'>Complete project 3-6.",
            color: "#994d99",
            complete() {return hasMilestone("prj", 306)},
            unlocked: true,
        },
        1221: {
            name: "Mind-numbing",
            image: "resources/achievements/12_19.png",
            tooltip: "<h3>Mind-numbing</h3><hr style='margin-bottom:4px'>Have 20 focus spent.",
            color: "#994d99",
            complete() {return player.prj.focused.gte(20)},
            unlocked: true,
        },
        1222: {
            name: "Outerspace",
            image: "resources/achievements/12_19.png",
            tooltip: "<h3>Outerspace</h3><hr style='margin-bottom:4px'>Enter space zone<br>IV.<br><br>Reward: +2 max<br>ship health.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1223: {
            name: "okay this is getting ridiculous",
            image: "resources/achievements/12_19.png",
            tooltip: "<h3>okay this is getting<br>ridiculous</h3><hr style='margin-bottom:4px'>Get at least 1 ↻ for each<br>of the first twelve<br>pyramid fountains.<br><br>Reward: Pyramid fountains<br>are 20% cheaper.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
            marked: true,
        },
        1224: {
            name: "Now What?",
            image: "resources/achievements/12_24.png",
            tooltip: "<h3>Now What?</h3><hr style='margin-bottom:4px'>Complete project 4-5.",
            color: "#994d99",
            complete() {return hasMilestone("prj", 405)},
            unlocked: true,
        },
        // Row 1: Unlock before prismatic
        // Row 2: Unlock before light well delta
        // Row 3: First few starshine runs
        // Row 4: Unlock before research projects
        1701: {
            name: "Level Two",
            image: "resources/achievements/17_01.png",
            tooltip: "<h3>Level Two</h3><hr style='margin-bottom:4px'>Unlock research projects.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1702: {
            name: "Busy Work",
            image: "resources/achievements/17_02.png",
            tooltip: "<h3>Busy Work</h3><hr style='margin-bottom:4px'>Reach a focus cap of 30.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1703: {
            name: "Lost In Time",
            image: "resources/achievements/17_03.png",
            tooltip: "<h3>Lost In Time</h3><hr style='margin-bottom:4px'>Unlock research projects.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1704: {
            name: "The Abyss",
            image: "resources/achievements/17_04.png",
            tooltip: "<h3>The Abyss</h3><hr style='margin-bottom:4px'>Obtain an ε ↻.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1705: {
            name: "???",
            image: "resources/achievements/17_05.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1706: {
            name: "???",
            image: "resources/achievements/17_06.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1707: {
            name: "How deep does it go?",
            image: "resources/achievements/17_07.png",
            tooltip: "<h3>How deep does it go?</h3><hr style='margin-bottom:4px'>Get at least 1 ↻ for each<br>of the first fourteen pyramid<br>fountains.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1708: {
            name: "???",
            image: "resources/achievements/17_08.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1709: {
            name: "???",
            image: "resources/achievements/17_09.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1710: {
            name: "???",
            image: "resources/achievements/17_10.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1711: {
            name: "???",
            image: "resources/achievements/17_11.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1712: {
            name: "???",
            image: "resources/achievements/17_12.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???.",
            color: "#994d99",
            complete() {return false},
            unlocked: true,
        },
        1713: {
            name: "Universeception",
            image: "resources/achievements/17_13.png",
            tooltip: "<h3>Universeception</h3><hr style='margin-bottom:4px'>Enter the cycle.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1714: {
            name: "Acclimatization",
            image: "resources/achievements/17_14.png",
            tooltip: "<h3>Acclimatization</h3><hr style='margin-bottom:4px'>Obtain a Β ↻.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1715: {
            name: "Mega Cycle",
            image: "resources/achievements/17_15.png",
            tooltip: "<h3>Mega Cycle</h3><hr style='margin-bottom:4px'>Do 10 cycle resets.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1716: {
            name: "Altitude Sickness",
            image: "resources/achievements/17_16.png",
            tooltip: "<h3>Altitude Sickness</h3><hr style='margin-bottom:4px'>Obtain a Γ ↻.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1717: {
            name: "???",
            image: "resources/achievements/17_17.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1718: {
            name: "???",
            image: "resources/achievements/17_18.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1719: {
            name: "The Purple Stuff",
            image: "resources/achievements/17_19.png",
            tooltip: "<h3>The Purple Stuff</h3><hr style='margin-bottom:4px'>Unlock planetarium.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1720: {
            name: "Automation if it was manual",
            image: "resources/achievements/17_20.png",
            tooltip: "<h3>Automation if it<br>was manual</h3><hr style='margin-bottom:4px'>Have a focus cap<br>of 100.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1721: {
            name: "Well Well Well...",
            image: "resources/achievements/17_21.png",
            tooltip: "<h3>Well Well Well...</h3><hr style='margin-bottom:4px'>Unlock starlight<br>well ι.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1722: {
            name: "???",
            image: "resources/achievements/17_22.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1723: {
            name: "???",
            image: "resources/achievements/17_23.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1724: {
            name: "The Purple Cycle",
            image: "resources/achievements/17_24.png",
            tooltip: "<h3>The Purple Cycle</h3><hr style='margin-bottom:4px'>Do 1,000 cycle<br>resets.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        // Row 1: Unlock before pyramid row 6
        // Row 2: Unlock before cycle
        // Row 3: Unlock before planetarium
        // Row 4: Unlock before starmetal enhancement
        /*
        1701: {
            name: "Universeception",
            image: "resources/achievements/17_01.png",
            tooltip: "<h3>Universeception</h3><hr style='margin-bottom:4px'>Enter the cycle.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1702: {
            name: "Acclimatization",
            image: "resources/achievements/17_02.png",
            tooltip: "<h3>Acclimatization</h3><hr style='margin-bottom:4px'>Obtain a Β ↻.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1703: {
            name: "Mega Cycle",
            image: "resources/achievements/17_03.png",
            tooltip: "<h3>Mega Cycle</h3><hr style='margin-bottom:4px'>Do 10 cycle resets.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1704: {
            name: "Altitude Sickness",
            image: "resources/achievements/17_04.png",
            tooltip: "<h3>Altitude Sickness</h3><hr style='margin-bottom:4px'>Obtain a Γ ↻.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1705: {
            name: "???",
            image: "resources/achievements/17_05.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1706: {
            name: "???",
            image: "resources/achievements/17_06.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1707: {
            name: "The Purple Stuff",
            image: "resources/achievements/17_07.png",
            tooltip: "<h3>The Purple Stuff</h3><hr style='margin-bottom:4px'>Unlock planetarium.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1708: {
            name: "Automation if it was manual",
            image: "resources/achievements/17_08.png",
            tooltip: "<h3>Automation if it<br>was manual</h3><hr style='margin-bottom:4px'>Have a focus cap<br>of 100.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1709: {
            name: "Feature Dense",
            image: "resources/achievements/17_09.png",
            tooltip: "<h3>Feature Dense</h3><hr style='margin-bottom:4px'>Do an astro reset.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1710: {
            name: "Well Well Well...",
            image: "resources/achievements/17_10.png",
            tooltip: "<h3>Well Well Well...</h3><hr style='margin-bottom:4px'>Unlock starlight<br>well ι.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1711: {
            name: "???",
            image: "resources/achievements/17_11.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1712: {
            name: "The Purple Cycle",
            image: "resources/achievements/17_12.png",
            tooltip: "<h3>The Purple Cycle</h3><hr style='margin-bottom:4px'>Do 1,000 cycle<br>resets.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1713: {
            name: "Enhance! Again!",
            image: "resources/achievements/17_13.png",
            tooltip: "<h3>Enhance! Again!</h3><hr style='margin-bottom:4px'>Unlock starmetal<br>enhancement.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1714: {
            name: "???",
            image: "resources/achievements/17_14.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1715: {
            name: "???",
            image: "resources/achievements/17_15.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1716: {
            name: "???",
            image: "resources/achievements/17_16.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1717: {
            name: "???",
            image: "resources/achievements/17_17.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1718: {
            name: "???",
            image: "resources/achievements/17_18.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1719: {
            name: "Technically Technological",
            image: "resources/achievements/17_18.png",
            tooltip: "<h3>Technically Technological</h3><hr style='margin-bottom:4px'>Build the technological<br>pylon.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1720: {
            name: "???",
            image: "resources/achievements/17_20.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1721: {
            name: "???",
            image: "resources/achievements/17_18.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1722: {
            name: "???",
            image: "resources/achievements/17_22.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1723: {
            name: "???",
            image: "resources/achievements/17_23.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        1724: {
            name: "???",
            image: "resources/achievements/17_24.png",
            tooltip: "<h3>???</h3><hr style='margin-bottom:4px'>???",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },
        // Row 1: Unlock before planetarium
        // Row 2: Unlock before starmetal enhancement
        // Row 3: Unlock before the technological pylon
        // Row 4: Unlock before anti-singularity
        1901: {
            name: "Up The Anti",
            image: "resources/achievements/17_12.png",
            tooltip: "<h3>Up The Anti</h3><hr style='margin-bottom:4px'>Do an anti-singularity<br>reset.",
            color: "#994d73",
            complete() {return false},
            unlocked: true,
        },*/
    },
    tooltip: "Achievements",
    color: "white",
    microtabs: {
        stars: {
            1: { // Pre-Infinity
                unlocked: true,
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 1], ["achievement", 2], ["achievement", 3], ["achievement", 4], ["achievement", 5], ["achievement", 6],
                            ["achievement", 7], ["achievement", 8], ["achievement", 9], ["achievement", 10], ["achievement", 11], ["achievement", 12],
                            ["achievement", 13], ["achievement", 14], ["achievement", 15], ["achievement", 16], ["achievement", 17], ["achievement", 18],
                            ["achievement", 19], ["achievement", 20], ["achievement", 21], ["achievement", 22], ["achievement", 23], ["achievement", 24],
                        ]],
                    ], {width: "621px", height: "409px", background: "#111", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            2: { // Infinity & IP Challenges
                unlocked() {return hasAchievement("achievements", 101) || player.in.unlockedInfinity},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 101], ["achievement", 102], ["achievement", 103], ["achievement", 104], ["achievement", 105], ["achievement", 106],
                            ["achievement", 107], ["achievement", 108], ["achievement", 109], ["achievement", 110], ["achievement", 111], ["achievement", 112],
                            ["achievement", 113], ["achievement", 114], ["achievement", 115], ["achievement", 116], ["achievement", 117], ["achievement", 118],
                            ["achievement", 119], ["achievement", 120], ["achievement", 121], ["achievement", 122], ["achievement", 123], ["achievement", 124],
                        ]],
                    ], {width: "621px", height: "409px", background: "#191300", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            3: { // Tav & NIP
                unlocked() {return hasAchievement("achievements", 201) || (hasChallenge("ip", 18) || player.s.highestSingularityPoints.gt(0))},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 201], ["achievement", 202], ["achievement", 203], ["achievement", 204], ["achievement", 205], ["achievement", 206],
                            ["achievement", 207], ["achievement", 208], ["achievement", 209], ["achievement", 210], ["achievement", 211], ["achievement", 212],
                            ["achievement", 213], ["achievement", 214], ["achievement", 215], ["achievement", 216], ["achievement", 217], ["achievement", 218],
                            ["achievement", 219], ["achievement", 220], ["achievement", 221], ["achievement", 222], ["achievement", 223], ["achievement", 224],
                        ]],
                    ], {width: "621px", height: "409px", background: "#232b2b", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            4: { // Early Break Infinity
                unlocked() {return hasAchievement("achievements", 301) || player.in.unlockedBreak},
                content: [
                    ["top-column", [
                        ["raw-html", "WIP lol"],
                        /*
                        ["row", [
                            ["achievement", 301], ["achievement", 302], ["achievement", 303], ["achievement", 304], ["achievement", 305], ["achievement", 306],
                            ["achievement", 307], ["achievement", 308], ["achievement", 309], ["achievement", 310], ["achievement", 311], ["achievement", 312],
                            ["achievement", 313], ["achievement", 314], ["achievement", 315], ["achievement", 316], ["achievement", 317], ["achievement", 318],
                            ["achievement", 319], ["achievement", 320], ["achievement", 321], ["achievement", 322], ["achievement", 323], ["achievement", 324],
                        ]],
                        */
                    ], {width: "621px", height: "409px", background: "#081902", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            5: { // Late BI, Cante, and Alt-Uni 1
                unlocked() {return hasAchievement("achievements", 401) || (hasUpgrade("bi", 24) || player.s.highestSingularityPoints.gt(0))},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 401], ["achievement", 402], ["achievement", 403], ["achievement", 404], ["achievement", 405], ["achievement", 406],
                            ["achievement", 407], ["achievement", 408], ["achievement", 409], ["achievement", 410], ["achievement", 411], ["achievement", 412],
                            ["achievement", 413], ["achievement", 414], ["achievement", 415], ["achievement", 416], ["achievement", 417], ["achievement", 418],
                            ["achievement", 419], ["achievement", 420], ["achievement", 421], ["achievement", 422], ["achievement", 423], ["achievement", 424],
                        ]],
                    ], {width: "621px", height: "409px", background: "#021a25", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            6: { // Early Singularity and Jocus
                unlocked() {return hasAchievement("achievements", 501) || player.s.highestSingularityPoints.gt(0)},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 501], ["achievement", 502], ["achievement", 503], ["achievement", 504], ["achievement", 505], ["achievement", 506],
                            ["achievement", 507], ["achievement", 508], ["achievement", 509], ["achievement", 510], ["achievement", 511], ["achievement", 512],
                            ["achievement", 513], ["achievement", 514], ["achievement", 515], ["achievement", 516], ["achievement", 517], ["achievement", 518],
                            ["achievement", 519], ["achievement", 520], ["achievement", 521], ["achievement", 522], ["achievement", 523], ["achievement", 524],
                        ]],
                    ], {width: "621px", height: "409px", background: "#190606", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            7: { // Starmetal Alloy, Dark-Uni 1, and Punchcards
                unlocked() {return hasAchievement("achievements", 601) || hasUpgrade("s", 21)},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 601], ["achievement", 602], ["achievement", 603], ["achievement", 604], ["achievement", 605], ["achievement", 606],
                            ["achievement", 607], ["achievement", 608], ["achievement", 609], ["achievement", 610], ["achievement", 611], ["achievement", 612],
                            ["achievement", 613], ["achievement", 614], ["achievement", 615], ["achievement", 616], ["achievement", 617], ["achievement", 618],
                            ["achievement", 619], ["achievement", 620], ["achievement", 621], ["achievement", 622], ["achievement", 623], ["achievement", 624],
                        ]],
                    ], {width: "621px", height: "409px", background: "#000", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            8: { // Matos and Early Black Heart
                unlocked() {return hasAchievement("achievements", 701) || tmp.pu.levelables[302].canClick},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 701], ["achievement", 702], ["achievement", 703], ["achievement", 704], ["achievement", 705], ["achievement", 706],
                            ["achievement", 707], ["achievement", 708], ["achievement", 709], ["achievement", 710], ["achievement", 711], ["achievement", 712],
                            ["achievement", 713], ["achievement", 714], ["achievement", 715], ["achievement", 716], ["achievement", 717], ["achievement", 718],
                            ["achievement", 719], ["achievement", 720], ["achievement", 721], ["achievement", 722], ["achievement", 723], ["achievement", 724],
                        ]],
                    ], {width: "621px", height: "409px", background: "#1b0218", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            9: { // Alt-Uni 2 and Iridite
                unlocked() {return hasAchievement("achievements", 801) || player.matosLair.milestone[25] > 0},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 801], ["achievement", 802], ["achievement", 803], ["achievement", 804], ["achievement", 805], ["achievement", 806],
                            ["achievement", 807], ["achievement", 808], ["achievement", 809], ["achievement", 810], ["achievement", 811], ["achievement", 812],
                            ["achievement", 813], ["achievement", 814], ["achievement", 815], ["achievement", 816], ["achievement", 817], ["achievement", 818],
                            ["achievement", 819], ["achievement", 820], ["achievement", 821], ["achievement", 822], ["achievement", 823], ["achievement", 824],
                        ]],
                    ], {width: "621px", height: "409px", background: "#0b011c", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            10: { // Early-Mid Hive
                unlocked() {return hasAchievement("achievements", 901) || player.pol.unlockHive >= 2},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 901], ["achievement", 902], ["achievement", 903], ["achievement", 904], ["achievement", 905], ["achievement", 906],
                            ["achievement", 907], ["achievement", 908], ["achievement", 909], ["achievement", 910], ["achievement", 911], ["achievement", 912],
                            ["achievement", 913], ["achievement", 914], ["achievement", 915], ["achievement", 916], ["achievement", 917], ["achievement", 918],
                            ["achievement", 919], ["achievement", 920], ["achievement", 921], ["achievement", 922], ["achievement", 923], ["achievement", 924],
                        ]],
                    ], {width: "621px", height: "409px", background: "#191000", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            11: {
                unlocked() {return true},
                content: [
                    ["top-column", [
                        ["row", [
                            
                        ]],
                    ], {width: "621px", height: "409px", background: "#333", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            12: {
                unlocked() {return true},
                content: [
                    ["top-column", [
                        ["row", [
                            
                        ]],
                    ], {width: "621px", height: "409px", background: "#333", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            13: { // Interspace before research projects
                unlocked() {return hasAchievement("achievements", 1201) || player.lightRift.interspaceUnlocked},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 1201], ["achievement", 1202], ["achievement", 1203], ["achievement", 1204], ["achievement", 1205], ["achievement", 1206],
                            ["achievement", 1207], ["achievement", 1208], ["achievement", 1209], ["achievement", 1210], ["achievement", 1211], ["achievement", 1212],
                            ["achievement", 1213], ["achievement", 1214], ["achievement", 1215], ["achievement", 1216], ["achievement", 1217], ["achievement", 1218],
                            ["achievement", 1219], ["achievement", 1220], ["achievement", 1221], ["achievement", 1222], ["achievement", 1223], ["achievement", 1224],
                        ]],
                    ], {width: "621px", height: "409px", background: "#1f0e1f", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            14: {
                unlocked() {return true},
                content: [
                    ["top-column", [
                        ["row", [
                            
                        ]],
                    ], {width: "621px", height: "409px", background: "#333", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            15: {
                unlocked() {return true},
                content: [
                    ["top-column", [
                        ["row", [
                            
                        ]],
                    ], {width: "621px", height: "409px", background: "#333", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            16: {
                unlocked() {return true},
                content: [
                    ["top-column", [
                        ["row", [
                            
                        ]],
                    ], {width: "621px", height: "409px", background: "#333", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            17: { // Interspace after research projects, before unlocking starmetal enhancement
                unlocked() {return hasAchievement("achievements", 1701) || true},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 1701], ["achievement", 1702], ["achievement", 1703], ["achievement", 1704], ["achievement", 1705], ["achievement", 1706],
                            ["achievement", 1707], ["achievement", 1708], ["achievement", 1709], ["achievement", 1710], ["achievement", 1711], ["achievement", 1712],
                            ["achievement", 1713], ["achievement", 1714], ["achievement", 1715], ["achievement", 1716], ["achievement", 1717], ["achievement", 1718],
                            ["achievement", 1719], ["achievement", 1720], ["achievement", 1721], ["achievement", 1722], ["achievement", 1723], ["achievement", 1724],
                        ]],
                    ], {width: "621px", height: "409px", background: "#1f0e16", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            16: {
                unlocked() {return true},
                content: [
                    ["top-column", [
                        ["row", [
                            
                        ]],
                    ], {width: "621px", height: "409px", background: "#333", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
            19: { // Interspace after unlocking starmetal enhancement
                unlocked() {return hasAchievement("achievements", 1901) || true},
                content: [
                    ["top-column", [
                        ["row", [
                            ["achievement", 1901], ["achievement", 1902], ["achievement", 1903], ["achievement", 1904], ["achievement", 1905], ["achievement", 1906],
                            ["achievement", 1907], ["achievement", 1908], ["achievement", 1909], ["achievement", 1910], ["achievement", 1911], ["achievement", 1912],
                            ["achievement", 1913], ["achievement", 1914], ["achievement", 1915], ["achievement", 1916], ["achievement", 1917], ["achievement", 1918],
                            ["achievement", 1919], ["achievement", 1920], ["achievement", 1921], ["achievement", 1922], ["achievement", 1923], ["achievement", 1924],
                        ]],
                    ], {width: "621px", height: "409px", background: "#1f0e0e", borderLeft: "3px solid white", padding: "3px"}],
                ],
            },
        },
    },
    tabFormat: [
        ["style-column", [
            ["raw-html", "Achievements", {color: "white", fontSize: "30px", fontFamily: "monospace"}],
        ], {width: "800px", height: "50px", backgroundColor: "rgba(0,0,0,0.5)", borderTop: "3px solid white", borderLeft: "3px solid white", borderRight: "3px solid white", borderRadius: "25px 25px 0 0"}],
        ["style-row", [
            ["always-scroll-column", [
                ["style-row", [
                    ["category-button", ["~ 1 ~<br><h6>Start</h6>", "stars", 1], {width: "155px", height: "40px", color: "white", background: "#333", borderRight: "3px solid white"}],
                ], {width: "155px", height: "40px", borderBottom: "3px solid white"}],
                ["style-row", [
                    ["category-button", ["~ 2 ~<br><h6>Infinity</h6>", "stars", 2], {width: "155px", height: "40px", color: "#ffbf00", background: "#332600", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[2].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 3 ~<br><h6>Tav</h6>", "stars", 3], {width: "155px", height: "40px", color: "#b2d8d8", background: "#354040", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[3].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                /*
                ["style-row", [
                    ["category-button", ["~ 4 ~<br><h6>Break Infinity</h6>", "stars", 4], {width: "155px", height: "40px", color: "#2b7f0a", background: "#113204", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[4].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 5 ~<br><h6>Cante</h6>", "stars", 5], {width: "155px", height: "40px", color: "#43aad9", background: "#032737", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[5].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 6 ~<br><h6>Singularity</h6>", "stars", 6], {width: "155px", height: "40px", color: "#aa0000", background: "#330d0d", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[6].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 7 ~<br><h6>Starmetal</h6>", "stars", 7], {width: "155px", height: "40px", color: "#eb6077", background: "#111", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[7].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 8 ~<br><h6>Matos</h6>", "stars", 8], {width: "155px", height: "40px", color: "#8a0e79", background: "#370530", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[8].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 9 ~<br><h6>Iridite</h6>", "stars", 9], {width: "155px", height: "40px", color: "#5a4fcf", background: "#160239", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[9].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                */
                ["style-row", [
                    ["category-button", ["~ 10 ~<br><h6>Early Hive</h6>", "stars", 10], {width: "155px", height: "40px", color: "#f9c901", background: "#352300", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[10].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                /*
                ["style-row", [
                    ["category-button", ["~ 11 ~<br><h6>Dice Space</h6>", "stars", 11], {width: "155px", height: "40px", color: "#c0c0c0", background: "#606060", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[11].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 12 ~<br><h6>Late Hive</h6>", "stars", 12], {width: "155px", height: "40px", color: "#c0c0c0", background: "#606060", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[12].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                */
                ["style-row", [
                    ["category-button", ["~ 13 ~<br><h6>Early Interspace</h6>", "stars", 13], {width: "155px", height: "40px", color: "#e0ffe0", background: "#402040", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[13].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                /*
                ["style-row", [
                    ["category-button", ["~ 14 ~<br><h6>Early Tera</h6>", "stars", 14], {width: "155px", height: "40px", color: "#c0c0c0", background: "#606060", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[14].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 15 ~<br><h6>Aniciffo</h6>", "stars", 15], {width: "155px", height: "40px", color: "#c0c0c0", background: "#606060", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[15].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 16 ~<br><h6>Late Tera</h6>", "stars", 16], {width: "155px", height: "40px", color: "#c0c0c0", background: "#606060", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[16].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                */
               /*
                ["style-row", [
                    ["category-button", ["~ 17 ~<br><h6>Intermediate Interspace</h6>", "stars", 17], {width: "155px", height: "40px", color: "#e0ffff", background: "#402030", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[17].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                ["style-row", [
                    ["category-button", ["~ 19 ~<br><h6>Late Interspace</h6>", "stars", 19], {width: "155px", height: "40px", color: "#ffe0f0", background: "#402020", borderRight: "3px solid white"}],
                ], () => {return tmp.achievements.microtabs.stars[19].unlocked ? {width: "155px", height: "40px", borderBottom: "3px solid white"} : {display: "none !important"}}],
                */
                ], {width: "170px", height: "415px"}],
            ["style-column", [
                ["buttonless-microtabs", "stars", {borderWidth: "0"}],
            ], {width: "630px", height: "415px"}],
        ], {width: "800px", height: "415px", backgroundColor: "black", border: "3px solid white"}],
        ["style-column", [
            ["raw-html", "Achievements with a green border can be clicked to obtain.", {color: "white", fontSize: "18px", fontFamily: "monospace"}],
        ], {width: "800px", height: "30px", backgroundColor: "rgba(0,0,0,0.5)", borderLeft: "3px solid white", borderRight: "3px solid white", borderBottom: "1px solid white"}],
        ["style-column", [
            ["raw-html", "<span style='color:red'>WARNING:</span> Achievements are currently <span style='color:red'>WIP</span> and are missing pages and icons.", {color: "white", fontSize: "18px", fontFamily: "monospace"}],
            ["raw-html", "(They do give rewards though, so maybe look at them a little)", {color: "white", fontSize: "16px", fontFamily: "monospace"}],
        ], {width: "800px", height: "50px", backgroundColor: "rgba(0,0,0,0.5)", borderLeft: "3px solid white", borderRight: "3px solid white", borderBottom: "3px solid white", borderRadius: "0 0 25px 25px"}],
        ["blank", "25px"],
    ],
    layerShown() { return false }
})